from pokemon import *

POKEMONS = [
    FirePokemon("Chamander"),
    FirePokemon("Chameleon"),
    FirePokemon("Charizard"),
    FirePokemon("Flareon"),
    FirePokemon("Magmar"),
    FirePokemon("Ponyta"),
    FirePokemon("Rapidash"),
    FirePokemon("Moltres"),
    WaterPokemon("Squirtle"),
    WaterPokemon("Wartotle"),
    WaterPokemon("Blastoise"),
    WaterPokemon("Goldeen"),
    WaterPokemon("Seaking"),
    WaterPokemon("Shelder"),
    WaterPokemon("Cloyster"),
    WaterPokemon("Articuno"),
    ElectricPokemon("Pikachu"),
    ElectricPokemon("Raichu"),
    ElectricPokemon("Magneton"),
    ElectricPokemon("Magnemite"),
    ElectricPokemon("Voltorb"),
    ElectricPokemon("Electrode"),
    ElectricPokemon("Electabuzz"),
    ElectricPokemon("Zapdos"),
    GrassPokemon("Bulbasaur"),
    GrassPokemon("Ivysaur"),
    GrassPokemon("Venusaur"),
    GrassPokemon("Scyther"),
    GrassPokemon("Oddish"),
    GrassPokemon("Gloom"),
    GrassPokemon("Vileplume"),
    ]